licenses(['permissive'])
package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'optional',
  srcs = glob(['optional/*']),
  hdrs = ['optional.hpp'],
  includes = ['..'],
  linkstatic = 1
)
